/**
 * One-time backfill: recompute the destination arrival/estimatedArrival for
 * existing FUTURE SCHEDULED trips using the corrected `computeDestinationArrivalOffset`
 * logic (OT1: "0h 0m everywhere"). Future trips generated by the rolling job are
 * already correct after the generator fix; this repairs trips already in the DB.
 *
 *   dry run (read-only): pnpm --filter web tsx scripts/backfill-trip-durations.ts
 *   apply (writes TripStop + Trip rows): APPLY=1 pnpm --filter web tsx scripts/backfill-trip-durations.ts
 *
 * Idempotent and time-bounded: only `SCHEDULED` trips departing on/after today,
 * batched. Skips trips whose values are already correct.
 */
import { getPrismaClient } from "@moja/db";
import { startOfAppCalendarDay } from "../lib/timezone";
import { computeDestinationArrivalOffset } from "../lib/trip-destination";

const APPLY = Boolean(process.env["APPLY"]);
const BATCH = 200;

async function main() {
  const prisma = getPrismaClient();
  const cutoff = startOfAppCalendarDay(new Date());

  let scanned = 0;
  let changed = 0;
  const sample: Array<{
    tripId: string;
    departureDate: Date;
    oldArrival: Date;
    oldEstimatedArrival: Date;
    newArrival: Date;
  }> = [];

  const total = await prisma.trip.count({
    where: {
      status: "SCHEDULED",
      departureDate: { gte: cutoff },
      archivedAt: null,
    },
  });

  for (let skip = 0; skip < total; skip += BATCH) {
    const trips = await prisma.trip.findMany({
      where: {
        status: "SCHEDULED",
        departureDate: { gte: cutoff },
        archivedAt: null,
      },
      select: {
        id: true,
        scheduleId: true,
        departureDate: true,
        estimatedArrival: true,
        schedule: {
          select: {
            route: {
              select: {
                waypoints: {
                  select: {
                    id: true,
                    stopOrder: true,
                    distanceFromOriginKm: true,
                  },
                },
              },
            },
            scheduleWaypoints: {
              select: {
                routeWaypointId: true,
                arrivalOffsetMinutes: true,
                departureOffsetMinutes: true,
              },
            },
            fares: {
              where: { fromStopOrder: 0, isActive: true },
              select: { toStopOrder: true, durationMinutes: true },
            },
          },
        },
        tripStops: {
          where: { isDropoff: true },
          select: {
            id: true,
            stopOrder: true,
            scheduledArrival: true,
            scheduledDeparture: true,
          },
        },
      },
      orderBy: { departureDate: "asc" },
      take: BATCH,
      skip,
    });

    for (const trip of trips) {
      scanned++;
      const lastWp =
        trip.schedule.route.waypoints.length > 0
          ? trip.schedule.route.waypoints.at(-1)
          : undefined;
      const destStopOrder = (lastWp?.stopOrder ?? 0) + 1;

      const fullRouteFare = trip.schedule.fares.find(
        (f) => f.toStopOrder === destStopOrder,
      );
      const fullRouteDurationMin = fullRouteFare?.durationMinutes ?? null;

      const waypoints = trip.schedule.route.waypoints.map((w) => ({
        id: w.id,
        stopOrder: w.stopOrder,
      }));
      const timings = new Map(
        trip.schedule.scheduleWaypoints.map((sw) => [
          sw.routeWaypointId,
          {
            arrivalOffsetMinutes: sw.arrivalOffsetMinutes,
            departureOffsetMinutes: sw.departureOffsetMinutes,
          },
        ]),
      );

      const destOffset = computeDestinationArrivalOffset({
        waypoints,
        timings,
        fullRouteDurationMin,
      });
      const newArrival = new Date(
        trip.departureDate.getTime() + destOffset * 60000,
      );

      const destStop =
        trip.tripStops.length > 0
          ? trip.tripStops.reduce((max, s) =>
              s.stopOrder > max.stopOrder ? s : max,
            )
          : undefined;

      if (!destStop) {
        continue;
      }

      const alreadyCorrect =
        destStop.scheduledArrival.getTime() === newArrival.getTime() &&
        destStop.scheduledDeparture.getTime() === newArrival.getTime() &&
        trip.estimatedArrival?.getTime() === newArrival.getTime();

      if (alreadyCorrect) {
        continue;
      }

      changed++;
      if (sample.length < 10) {
        sample.push({
          tripId: trip.id,
          departureDate: trip.departureDate,
          oldArrival: destStop.scheduledArrival,
          oldEstimatedArrival:
            trip.estimatedArrival ?? destStop.scheduledArrival,
          newArrival,
        });
      }

      if (APPLY) {
        await prisma.$transaction(async (tx) => {
          await tx.tripStop.update({
            where: { id: destStop.id },
            data: {
              scheduledArrival: newArrival,
              scheduledDeparture: newArrival,
            },
          });
          await tx.trip.update({
            where: { id: trip.id },
            data: { estimatedArrival: newArrival },
          });
        });
      }
    }
  }

  console.log(
    JSON.stringify(
      {
        dryRun: !APPLY,
        cutoff: cutoff.toISOString(),
        totalFutureScheduled: total,
        scanned,
        changed,
        sample,
      },
      null,
      2,
    ),
  );
  await prisma.$disconnect();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
