/**
 * Test fixtures mirroring the geo importer (packages/db/scripts/import-ivory-coast-geo.ts),
 * which is the single source of truth for the Côte d'Ivoire city / municipality /
 * quarter dataset. Only Abidjan has real municipalities (communes) with quarters;
 * every other city gets a single pass-through municipality named after the city
 * itself. This list matches the 188 cities produced by the importer.
 */

export const seedCities = [
  { name: "Abengourou", isMajorHub: false },
  { name: "Abidjan", isMajorHub: true },
  { name: "Aboisso", isMajorHub: false },
  { name: "Adiaké", isMajorHub: false },
  { name: "Adzopé", isMajorHub: false },
  { name: "Agboville", isMajorHub: false },
  { name: "Agnibilékrou", isMajorHub: false },
  { name: "Akoupé", isMajorHub: false },
  { name: "Alépé", isMajorHub: false },
  { name: "Aniassué", isMajorHub: false },
  { name: "Anyama", isMajorHub: false },
  { name: "Aprompronou", isMajorHub: false },
  { name: "Arrah", isMajorHub: false },
  { name: "Attinguié", isMajorHub: false },
  { name: "Attiégouakro", isMajorHub: false },
  { name: "Ayamé", isMajorHub: false },
  { name: "Banabo", isMajorHub: false },
  { name: "Bangolo", isMajorHub: false },
  { name: "Belleville", isMajorHub: false },
  { name: "Bettié", isMajorHub: false },
  { name: "Biankouma", isMajorHub: false },
  { name: "Bin-Houyé", isMajorHub: false },
  { name: "Bingerville", isMajorHub: false },
  { name: "Blapleu", isMajorHub: false },
  { name: "Bloléquin", isMajorHub: false },
  { name: "Bocanda", isMajorHub: false },
  { name: "Bodo", isMajorHub: false },
  { name: "Bogofa", isMajorHub: false },
  { name: "Bondoukou", isMajorHub: false },
  { name: "Bongouanou", isMajorHub: false },
  { name: "Bonon", isMajorHub: false },
  { name: "Bonoua", isMajorHub: false },
  { name: "Bonoufla", isMajorHub: false },
  { name: "Botro", isMajorHub: false },
  { name: "Bouaflé", isMajorHub: false },
  { name: "Bouaké", isMajorHub: true },
  { name: "Bouna", isMajorHub: false },
  { name: "Boundiali", isMajorHub: false },
  { name: "Buyo", isMajorHub: false },
  { name: "Béoumi", isMajorHub: false },
  { name: "Céchi", isMajorHub: false },
  { name: "Dabakala", isMajorHub: false },
  { name: "Dabou", isMajorHub: false },
  { name: "Dadiesso", isMajorHub: false },
  { name: "Dahiri", isMajorHub: false },
  { name: "Dalao", isMajorHub: false },
  { name: "Daloa", isMajorHub: true },
  { name: "Danané", isMajorHub: false },
  { name: "Dania", isMajorHub: false },
  { name: "Daoukro", isMajorHub: false },
  { name: "Diabo", isMajorHub: false },
  { name: "Diafla", isMajorHub: false },
  { name: "Dianra", isMajorHub: false },
  { name: "Didiévi", isMajorHub: false },
  { name: "Dikodougou", isMajorHub: false },
  { name: "Dimbokro", isMajorHub: false },
  { name: "Divo", isMajorHub: false },
  { name: "Diégonéfla", isMajorHub: false },
  { name: "Djekanou", isMajorHub: false },
  { name: "Doba", isMajorHub: false },
  { name: "Dogbo", isMajorHub: false },
  { name: "Doropo", isMajorHub: false },
  { name: "Doukouya", isMajorHub: false },
  { name: "Duékoué", isMajorHub: false },
  { name: "Facobly", isMajorHub: false },
  { name: "Ferkéssédougou", isMajorHub: false },
  { name: "Foumbolo", isMajorHub: false },
  { name: "Fresco", isMajorHub: false },
  { name: "Fronan", isMajorHub: false },
  { name: "Gabiadji", isMajorHub: false },
  { name: "Gadouan", isMajorHub: false },
  { name: "Gagnoa", isMajorHub: false },
  { name: "Gbeleban", isMajorHub: false },
  { name: "Gbolouville", isMajorHub: false },
  { name: "Gohitafla", isMajorHub: false },
  { name: "Gomon", isMajorHub: false },
  { name: "Gonaté", isMajorHub: false },
  { name: "Goudi", isMajorHub: false },
  { name: "Gouéya", isMajorHub: false },
  { name: "Grand-Bassam", isMajorHub: false },
  { name: "Grand-Béréby", isMajorHub: false },
  { name: "Grand-Lahou", isMajorHub: false },
  { name: "Grand-Zattry", isMajorHub: false },
  { name: "Grosso (Ancien Prozi)", isMajorHub: false },
  { name: "Guibéroua", isMajorHub: false },
  { name: "Guiglo", isMajorHub: false },
  { name: "Guitry", isMajorHub: false },
  { name: "Guépahouo", isMajorHub: false },
  { name: "Guéyo", isMajorHub: false },
  { name: "Hermankono Garo", isMajorHub: false },
  { name: "Hiré", isMajorHub: false },
  { name: "Iboguhé", isMajorHub: false },
  { name: "Issia", isMajorHub: false },
  { name: "Jacqueville", isMajorHub: false },
  { name: "Kadarvogo", isMajorHub: false },
  { name: "Kahin-Zarabaon", isMajorHub: false },
  { name: "Kani", isMajorHub: false },
  { name: "Kaniasso", isMajorHub: false },
  { name: "Katiola", isMajorHub: false },
  { name: "Kong", isMajorHub: false },
  { name: "Kononfla", isMajorHub: false },
  { name: "Korhogo", isMajorHub: true },
  { name: "Koro", isMajorHub: false },
  { name: "Korogho", isMajorHub: false },
  { name: "Kossou", isMajorHub: false },
  { name: "Kouassi-Kouassikr", isMajorHub: false },
  { name: "Kouassi-Kouassikro", isMajorHub: false },
  { name: "Kouibly", isMajorHub: false },
  { name: "Koun-Fao", isMajorHub: false },
  { name: "Kounahiri", isMajorHub: false },
  { name: "Kouto", isMajorHub: false },
  { name: "Krinjabo", isMajorHub: false },
  { name: "Lakota", isMajorHub: false },
  { name: "Lataha", isMajorHub: false },
  { name: "Lessiri", isMajorHub: false },
  { name: "Lolobo", isMajorHub: false },
  { name: "M'bahiakro", isMajorHub: false },
  { name: "Madinani", isMajorHub: false },
  { name: "Man", isMajorHub: true },
  { name: "Mankono", isMajorHub: false },
  { name: "Minignan", isMajorHub: false },
  { name: "Minoré", isMajorHub: false },
  { name: "Moussue", isMajorHub: false },
  { name: "Méagui", isMajorHub: false },
  { name: "M’Batto", isMajorHub: false },
  { name: "M’Bengué", isMajorHub: false },
  { name: "Napié", isMajorHub: false },
  { name: "Nassian", isMajorHub: false },
  { name: "Niakaramandougou", isMajorHub: false },
  { name: "Niellé", isMajorHub: false },
  { name: "Niéméné", isMajorHub: false },
  { name: "Nyameasa", isMajorHub: false },
  { name: "N’Douci", isMajorHub: false },
  { name: "Odienné", isMajorHub: false },
  { name: "Okrouyo", isMajorHub: false },
  { name: "Ouangolodougou", isMajorHub: false },
  { name: "Ouaninou", isMajorHub: false },
  { name: "Oumé", isMajorHub: false },
  { name: "Ouragahio", isMajorHub: false },
  { name: "Prikro", isMajorHub: false },
  { name: "Rubino", isMajorHub: false },
  { name: "Sago", isMajorHub: false },
  { name: "Sakassou", isMajorHub: false },
  { name: "Samatiguila", isMajorHub: false },
  { name: "San-Pédro", isMajorHub: true },
  { name: "Sandegue", isMajorHub: false },
  { name: "Sassandra", isMajorHub: false },
  { name: "Saïoua", isMajorHub: false },
  { name: "Seguelon", isMajorHub: false },
  { name: "Siempurgo", isMajorHub: false },
  { name: "Sifié", isMajorHub: false },
  { name: "Sikensi", isMajorHub: false },
  { name: "Sinfra", isMajorHub: false },
  { name: "Sinématiali", isMajorHub: false },
  { name: "Sipilou", isMajorHub: false },
  { name: "Songon", isMajorHub: false },
  { name: "Soubré", isMajorHub: false },
  { name: "Séguéla", isMajorHub: false },
  { name: "Séitifla", isMajorHub: false },
  { name: "Taabo", isMajorHub: false },
  { name: "Tabou", isMajorHub: false },
  { name: "Tafiré", isMajorHub: false },
  { name: "Tanda", isMajorHub: false },
  { name: "Taï", isMajorHub: false },
  { name: "Tehini", isMajorHub: false },
  { name: "Tengréla", isMajorHub: false },
  { name: "Tiapoum", isMajorHub: false },
  { name: "Tiassalé", isMajorHub: false },
  { name: "Tié-N’Diékro", isMajorHub: false },
  { name: "Tiébissou", isMajorHub: false },
  { name: "Tiéme", isMajorHub: false },
  { name: "Tiéningboué", isMajorHub: false },
  { name: "Tortiya", isMajorHub: false },
  { name: "Touba", isMajorHub: false },
  { name: "Touih", isMajorHub: false },
  { name: "Toulépleu", isMajorHub: false },
  { name: "Toumodi", isMajorHub: false },
  { name: "Transua", isMajorHub: false },
  { name: "Vaafla", isMajorHub: false },
  { name: "Vaou", isMajorHub: false },
  { name: "Vavoua", isMajorHub: false },
  { name: "Yakassé-Attobrou", isMajorHub: false },
  { name: "Yakassé-Féyassé", isMajorHub: false },
  { name: "Yamoussoukro", isMajorHub: true },
  { name: "Zagné", isMajorHub: false },
  { name: "Zouan-Hounien", isMajorHub: false },
  { name: "Zoukougbeu", isMajorHub: false },
  { name: "Zuénoula", isMajorHub: false },
] as const;

/** Abidjan's municipalities (communes) and their quarters (from the geo importer). */
export const seedAbidjanMunicipalities: {
  name: string;
  quarters: string[];
}[] = [
  {
    name: "Abobo",
    quarters: [
      "Abobo Baoule",
      "Abobo Sagbe",
      "Abobo Te",
      "Agbekoi",
      "Anonkoi 2",
      "Gare Abobo",
    ],
  },
  {
    name: "Adjamé",
    quarters: [
      "Adjamé Liberté",
      "Adjamé village",
      "Anador",
      "Attié",
      "Djinou",
      "Monsieur",
    ],
  },
  {
    name: "Attécoubé",
    quarters: [
      "Abia",
      "Agbo",
      "Ahongbon",
      "Attecoube Centre",
      "Baco",
      "Camp Militaire",
      "Dogosso",
      "Gare Attecoube",
    ],
  },
  {
    name: "Cocody",
    quarters: [
      "Angré",
      "Blokosso",
      "Bonie",
      "Cocody Centre",
      "Danga",
      "Deux-Plateaux",
      "M'Badon",
      "Palmeraie",
      "Riviera 2",
      "Riviera 3",
      "Riviera 4",
      "Saint-Jean",
    ],
  },
  {
    name: "Koumassi",
    quarters: [
      "Koumassi Campement",
      "Koumassi Gare",
      "Koumassi Marché",
      "Koumassi Nord",
      "Koumassi Remblais",
      "Koumassi Sud",
      "Petite Koumassi",
    ],
  },
  {
    name: "Marcory",
    quarters: [
      "Anoumabo",
      "Marcory Avenue 3",
      "Marcory Gare",
      "Marcory Nord",
      "Marcory Sud",
      "Marcory Zone 4",
    ],
  },
  {
    name: "Plateau",
    quarters: ["Le Plateau", "Plateau Centre", "Plateau Gare", "Plateau Nord"],
  },
  {
    name: "Port-Bouët",
    quarters: [
      "Abidjan Port",
      "Gare Port-Bouet",
      "Koumassi Port",
      "Port Bouet Centre",
      "Vridi",
      "Vridi Gare",
    ],
  },
  {
    name: "Treichville",
    quarters: [
      "Belleville",
      "Djelan",
      "Ficgayo",
      "Gare Treichville",
      "Mobidoum",
      "Treichville Centre",
    ],
  },
  {
    name: "Yopougon",
    quarters: [
      "Andokoi",
      "Ayé",
      "Bel Air",
      "Camp Militaire",
      "Gare Yopougon",
      "Koute",
      "Nianguan",
      "Niangon",
      "Niangon Adiaho",
      "Selmer",
      "Sicogi",
      "Sodeci",
      "Toit Rouge",
      "Yopougon Centre",
    ],
  },
  {
    name: "Anyama",
    quarters: ["Anyama Centre", "Anyama Gare", "Anyama Nord"],
  },
  {
    name: "Bingerville",
    quarters: ["Bingerville Centre", "Bingerville Gare"],
  },
  {
    name: "Brodoukou",
    quarters: ["Brodoukou Centre"],
  },
];

/** All cities EXCEPT Abidjan receive a single pass-through municipality. */
export const seedPassThroughCities = seedCities.filter(
  (c) => c.name !== "Abidjan",
);
