// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Do not use getRequiredEnv / prisma env() here.
// `prisma generate` loads this file during postinstall (including EAS builds)
// and does not need a live database URL. Commands that connect (migrate, db push)
// still fail clearly when DATABASE_URL is missing.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // directUrl bypasses the Neon pooler for migrate/diff/pull commands.
    // Falls back to DATABASE_URL when unset (production uses a direct db:5432 URL anyway).
    directUrl: process.env["DATABASE_URL_DIRECT"] ?? process.env["DATABASE_URL"],
  },
});
